- hosts: ELK_Node
  connection: local
  serial: 1
  tasks:
   - command: /usr/bin/ssh-keyscan -t ecdsa {{ ansible_host }}  # ansible_host 변수에 host에 등록된 Node를 불러와서 대입
     register: keyscan                                          # 확인된 ELK_Node들의 키 값을 keyscan 변수에 저장

   - lineinfile:
      name=~/.ssh/known_hosts
      create=yes
      line={{ item }}                                           # keyscan 변수에 있는 값이 stdout_lines으로 출력되면 known_hosts 파일에 한줄씩 작성
     
     with_items:
      - "{{ keyscan.stdout_lines }}"
