---
# ansible-playbook Delete_rule_on_line.yml --extra-vars "CHAIN_NAME=체인명 LINE_NUM=삭제할 줄번호"
- name: Delete a rule on line
  become: yes
  hosts: localhost
  tasks:
   - iptables:
      chain: "{{ CHAIN_NAME }}"
      flush: yes
      rule_num: "{{ LINE_NUM }}"
