---
- name: Iptables initial configuration          # iptables 초기 설정
  hosts: ELK_Node
  become: yes
  tasks:
   - name: Setting default policy               # 기본 정책 설정 (INPUT, OUPUT 체인의 기본정책을 DROP으로 설정)
     iptables:
      chain: "{{ item }}"
      policy: DROP
      flush: yes
     with_items: [ 'INPUT', 'OUTPUT' ]
   - debug:
      msg: 
       - "{{ item }} chain setting complete"

   - name: Setting default policy               # 기본 정책 설정 (FORWARD 체인의 기본정책을 ACCEPT으로 설정)
     iptables:
      chain: FORWARD
      policy: ACCEPT
      flush: yes
   - debug:
      msg: 
       - "FORWARD chain setting complete"

   - name: ACCEPT SSH traffic
     iptables:
      chain: INPUT
      state: present
      protocol: tcp
      destination_port: 22
      src_range: 192.168.111.120-192.168.111.130
      jump: ACCEPT

   - iptables:
      chain: OUTPUT
      state: present
      protocol: tcp
      destination_port: 22
      dst_range: 192.168.111.120-192.168.111.130
      jump: ACCEPT
