---
- name: Iptables initial configuration          # iptables 초기 설정
  hosts: ELK_Node
  become: yes
  tasks:
   - name: Setting default policy               # 기본 정책 설정 (INPUT, OUPUT 체인의 기본정책을 DROP으로 설정)
     iptables:
      chain: "{{ item }}"
      policy: ACCEPT
     with_items: [ 'INPUT', 'OUTPUT' ]
   - debug:
      msg: 
       - "{{ item }} chain setting complete"
     with_items: [ 'INPUT', 'OUTPUT' ]

   - name: Setting default policy               # 기본 정책 설정 (FORWARD 체인의 기본정책을 ACCEPT으로 설정)
     iptables:
      chain: FORWARD
      policy: ACCEPT
   - debug:
      msg: 
       - "FORWARD chain setting complete"

   - name: Accept SSH traffic
     iptables:
      chain: INPUT
      state: present
      protocol: tcp
      destination_port: 22
      action: insert                        # 해당 정책 삽입
      rule_num: 1                           # 1번에 삽입
      jump: ACCEPT

   - iptables:
      chain: OUTPUT
      state: present
      protocol: tcp
      destination_port: 22
      action: insert
      rule_num: 1
      jump: ACCEPT
   - debug:
      msg: 
       - "Accept SSH traffic complete"

   - name: Accept ping
     iptables:
      chain: "{{ item }}"
      state: present
      protocol: icmp
      jump: ACCEPT
     with_items: [ 'INPUT', 'OUTPUT' ]
   - debug:
      msg: 
       - "Accept ping complete"
