---
- name: Setting Log
  hosts: localhost
  become: yes
  tasks:
   - iptables:
      chain: INPUT
      jump: LOG
      protocol: tcp
      destination_port: 80,443
      action: append
      state: present
      ctstate: "NEW,ESTABLISHED"
      match: "multiport,conntrack"
      limit: 2/second
      limit_burst: 20
      log_prefix: "HTTP Log : "
      log_level: info
